Virtuemart plugin delivery address (France/belgium) fix
paynl/virtuemart3-plugin pull request #5
Opened 2020-12-07 14:43 UTC by bryantvandenberg

2020-12-15 07:37 UTC, kevinverschoor approved these changes

2020-12-28 16:00 UTC, woutse requested changes
Makes streetname empty

2021-01-07 07:43 UTC, kevinverschoor commented
Als een Adress een letter in het nummer heeft bijvoorbeeld 6a of 6b, dan gaat het mis en ziet hij **b** als de straatnaam

2021-01-07 09:01 UTC, kevinverschoor requested changes
Zie comment

2021-04-29 13:59 UTC, closed without merging